# Generated by Django 5.0.6 on 2024-05-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_registerno_student_registerno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='registerno',
            new_name='register_no',
        ),
    ]
